split lock files

diff --git a/apps/web/Dockerfile b/apps/web/Dockerfile
--- a/apps/web/Dockerfile
+++ b/apps/web/Dockerfile
@@ -7,11 +7,10 @@ RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
 # Install dependencies
-COPY ../../pnpm-lock.yaml ./pnpm-lock.yaml
-COPY package.json ./package.json
+COPY package.json pnpm-lock.yaml* ./
 RUN \
   if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
-  else echo "Root pnpm-lock.yaml not found." && exit 1; \
+  else echo "Lockfile not found." && exit 1; \
   fi
 
 
